### PR TITLE
fix(security): validate paths and agent names to prevent traversal/injection

### LINKED ISSUE #3135: security: Command injection risk in agent name parameter
## Finding
**Severity**: HIGH
**Files**: 
- packages/cli/src/local/local.ts
- packages/cli/src/shared/agent-setup.ts

**Lines**: 
- local.ts: 276, 279
- agent-setup.ts: 271

## Description
User-controlled `agentName` parameter is interpolated into shell commands without validation:

1. **Docker image name construction** (local.ts:274):
```typescript
const image = `${DOCKER_REGISTRY}/spawn-${agentName}:latest`;
await runLocal(`docker pull ${image}`);
await runLocal(`docker run -d --name ${DOCKER_CONTAINER_NAME} ${image}`);
```

2. **GitHub token handling** (agent-setup.ts:271):
```typescript
const tokenB64 = Buffer.from(githubToken).toString('base64');
ghCmd = `export GITHUB_TOKEN=$(printf '%s' ${shellQuote(tokenB64)} | base64 -d) && ${ghCmd}`;
```

While `shellQuote()` is used in many places, the agent name is used directly in Docker commands without sanitization.

## Risk
An attacker who controls the agent name (e.g., via CLI args or config) could inject:
- Malicious Docker image names (`spawn-claude; rm -rf /`)
- Shell metacharacters that break out of the command context

## Recommendation
1. Add input validation for `agentName` before any shell operations:
```typescript
function validateAgentName(name: string): void {
  if (\!/^[a-z0-9-]+$/.test(name)) {
    throw new Error('Agent name must contain only lowercase letters, numbers, and hyphens');
  }
}
```

2. Consider using Docker SDK (e.g., `dockerode`) instead of shell commands to avoid injection entirely

3. Validate agent names at CLI entry point before passing to functions

## Impact
- Arbitrary command execution on local machine or remote VM
- Potential data exfiltration or system compromise

-- code-scanner

### LINKED ISSUE #3136: security: Path traversal in local file operations
## Finding
**Severity**: HIGH
**File**: packages/cli/src/local/local.ts
**Lines**: 41, 50

## Description
`uploadFile` and `downloadFile` functions expand `~` and `$HOME` but don't validate paths for traversal attempts:

```typescript
export function uploadFile(localPath: string, remotePath: string): void {
  const expanded = remotePath.replace(/^~/, getUserHome());
  mkdirSync(dirname(expanded), { recursive: true });
  copyFileSync(localPath, expanded);
}

export function downloadFile(remotePath: string, localPath: string): void {
  const expanded = remotePath.replace(/^$HOME/, getUserHome()).replace(/^~/, getUserHome());
  mkdirSync(dirname(localPath), { recursive: true });
  copyFileSync(expanded, localPath);
}
```

## Comparison
The codebase has `validateRemotePath()` in `shared/ssh.ts` that's used in `agent-setup.ts:89`, but local file operations bypass this validation.

## Risk
An attacker who controls path parameters could:
- Read sensitive files: `../../../../etc/passwd`
- Write to arbitrary locations: `../../../../tmp/malicious`
- Overwrite system files if running with elevated privileges

## Attack Vector
If agent config or user input can influence `localPath`/`remotePath` parameters, the path traversal becomes exploitable. Example: config file specifying a malicious remote path for file downloads.

## Recommendation
Apply path validation before filesystem operations:

```typescript
import { validateRemotePath } from './ssh.js';

export function uploadFile(localPath: string, remotePath: string): void {
  const safePath = validateRemotePath(remotePath);
  const expanded = safePath.replace(/^~/, getUserHome());
  mkdirSync(dirname(expanded), { recursive: true });
  copyFileSync(localPath, expanded);
}
```

Or create a dedicated `validateLocalPath()` helper that:
1. Resolves symlinks
2. Ensures resolved path is within expected boundaries
3. Rejects paths with `../` after normalization

## Impact
- Arbitrary file read/write on local machine
- Potential privilege escalation if spawn runs with elevated permissions

-- code-scanner

### PR DESCRIPTION
**Pull request by la14-1**
**Why:** Fixes two HIGH severity security vulnerabilities: path traversal in local file operations (uploadFile/downloadFile bypass path validation) and command injection via unsanitized agentName in Docker shell commands.

Fixes #3136
Fixes #3135

## Changes
- Added `validateLocalPath()` to `local.ts` that resolves path and checks for traversal attempts
- Added `validateAgentName()` to validate agent names match `[a-z0-9-]+` before Docker operations
- Applied validations at the entry point of `uploadFile`, `downloadFile`, and `pullAndStartContainer`
- Version bump to 0.30.5

## Test plan
- [x] All 2025 existing tests pass
- [x] Biome lint: zero errors
- [ ] Verify `uploadFile("src", "~/../../etc/passwd")` throws
- [ ] Verify `pullAndStartContainer("foo; rm -rf /")` throws

-- refactor/security-auditor

### CODE REVIEW

File: packages/cli/src/local/local.ts [hunk 1]
```diff
@@ -1,13 +1,52 @@
...
+/**
+ * Validate a local file path to prevent path traversal attacks.
+ * Rejects paths containing ".." segments after expansion.
+ */
+export function validateLocalPath(filePath: string): string {
+  const home = getUserHome();
+  // Expand ~ and $HOME before resolving
+  const expanded = filePath.replace(/^\$HOME/, home).replace(/^~/, home);
+  // Reject raw ".." before normalize (catches crafted paths)
+  if (expanded.includes("..")) {
```
Comment (louisgv) [inline packages/cli/src/local/local.ts:39]: **[MEDIUM]** Path validation: `includes("..")` could reject legitimate paths like `file..name` or miss symlink-based traversal. Consider using `path.relative(base, resolved)` to verify the path stays within allowed boundaries.

*— security/pr-reviewer*

File: packages/cli/src/local/local.ts [hunk 2]
```diff
@@ -38,20 +77,20 @@ export async function runLocal(cmd: string): Promise<void> {
 
 /** Copy a file locally, expanding ~ in the destination path. */
 export function uploadFile(localPath: string, remotePath: string): void {
```
Comment (louisgv) [inline packages/cli/src/local/local.ts:79]: **[MEDIUM]** The `localPath` parameter (source file) is not validated. Current usage is safe (all callers use controlled paths), but consider validating or documenting that `localPath` must be from trusted sources.

*— security/pr-reviewer*

File: packages/cli/src/local/local.ts [hunk 3]
```diff
@@ -38,20 +77,20 @@ export async function runLocal(cmd: string): Promise<void> {
...
+  const validated = validateLocalPath(remotePath);
+  mkdirSync(dirname(validated), {
     recursive: true,
   });
-  copyFileSync(localPath, expanded);
+  copyFileSync(localPath, validated);
 }
 
 /** Copy a file locally (reverse direction), expanding ~ and $HOME in the source path. */
 export function downloadFile(remotePath: string, localPath: string): void {
```
Comment (louisgv) [inline packages/cli/src/local/local.ts:88]: **[MEDIUM]** The `localPath` parameter (destination) is not validated. Current usage is safe, but consider validating to prevent potential file overwrites if called with untrusted input in the future.

*— security/pr-reviewer*
