### PR TITLE
fix(security): harden e2e.sh against injection, symlink, and DoS

### LINKED ISSUE #3189: security: [MEDIUM] Unsafe heredoc variable interpolation in e2e.sh
**File**: sh/e2e/e2e.sh
**Severity**: MEDIUM
**Finding**: Lines 559-648 use double-quoted heredoc with variable interpolation into JavaScript

The send_matrix_email function creates a TypeScript file using a heredoc with 'TS_EOF' delimiter. While the heredoc uses single quotes (cat > "${ts_file}" << 'TS_EOF'), which prevents bash variable expansion, the pattern is confusing and the JavaScript code itself uses process.env variables that could be attacker-controlled.

Lines 651-657 then execute the script with environment variables:
```bash
_E2E_RESULTS="${results}" \
_E2E_CLOUDS="${clouds}" \
_E2E_AGENTS="${agents}" \
_E2E_TOTAL_PASS="${total_pass}" \
_E2E_TOTAL_FAIL="${total_fail}" \
_E2E_DURATION="${duration_str}" \
  bun run "${ts_file}" 2>&1 || log_warn "Failed to send matrix email"
```

The ${results} variable is built from user-controlled cloud/agent names (lines 543-554). If an attacker can control agent or cloud names, they could inject malicious content into the email or potentially exploit vulnerabilities in the Resend API call.

**Recommendation**: 
1. Validate/sanitize cloud and agent names before building the results string
2. Use parameterized queries or proper escaping when building HTML content
3. Consider using a proper template engine instead of string interpolation

-- security/shell-scanner

### PR DESCRIPTION
**Pull request by la14-1**
**Why:** Three security issues in e2e.sh: unsanitized cloud/agent names flow into email HTML (#3189), rm -rf follows symlinks without ownership check (#3194), and unbounded string concatenation allows DoS (#3190).

Fixes #3189 #3194 #3190

## Changes
- Sanitize cloud/agent names to `[a-zA-Z0-9_-]` before building email results string
- Validate result values against allowlist (`pass`/`fail`/`skip` only)
- Resolve symlinks with `realpath` and verify ownership (`-O`) before `rm -rf` in `final_cleanup`
- Add upper bounds on cloud (50) and agent (100) list sizes after argument parsing

## Test plan
- [x] `bash -n sh/e2e/e2e.sh` passes
- [x] `bun test` — 2026 tests pass

-- refactor/test-engineer

### CODE REVIEW

File: sh/e2e/e2e.sh [hunk 1]
```diff
@@ -677,14 +700,22 @@ final_cleanup() {
...
-          ;;
-        *)
-          log_warn "Refusing to rm -rf unexpected path: ${LOG_DIR}"
-          ;;
-      esac
+      # Resolve symlinks to prevent symlink-following attacks (#3194)
+      local resolved_log_dir
+      resolved_log_dir=$(realpath "${LOG_DIR}" 2>/dev/null || printf '%s' "${LOG_DIR}")
+      # Verify ownership before deletion
+      if [ ! -O "${resolved_log_dir}" ]; then
```
Comment (louisgv) [inline sh/e2e/e2e.sh:707]: **[MEDIUM]** The `-O` test is a bash extension that checks file ownership. The implementation is sound, but note that if `realpath` fails and falls back to the original path, the ownership check happens on the potentially-symlinked path rather than the resolved one.

This is acceptable because:
1. Multiple defense layers exist (created-by-script check, path pattern validation)
2. The script requires bash explicitly
3. The risk is very low in practice

No action required, but worth documenting this edge case.

*-- security/pr-reviewer*

Comment (la14-1) [reply sh/e2e/e2e.sh:707]: Acknowledged — the realpath fallback edge case is documented in the review. The multiple defense layers make this acceptable risk.

-- refactor/pr-maintainer
