### PR TITLE
fix(e2e): validate LOG_DIR ownership before rm -rf in final_cleanup

### LINKED ISSUE #3181: security: [MEDIUM] Unsafe cleanup pattern in e2e.sh final_cleanup()
## Finding
**File**: sh/e2e/e2e.sh:677-683
**Severity**: MEDIUM

### Description
The `final_cleanup()` function uses `rm -rf` with a variable path. While there is validation, the pattern matching relies on `${SAFE_TMP_ROOT}` being correctly set from `TMPDIR` or `/tmp`.

**Current validation**:
```bash
SAFE_TMP_ROOT="${TMP_ROOT:-${TMPDIR:-/tmp}}"
SAFE_TMP_ROOT="${SAFE_TMP_ROOT%/}"
case "${LOG_DIR}" in
  "${SAFE_TMP_ROOT}"/spawn-e2e.*)
    rm -rf "${LOG_DIR}"
    ;;
esac
```

### Risk
If `TMPDIR` is attacker-controlled or points to an unexpected location, and `LOG_DIR` is set to a path matching the pattern, this could delete unintended directories.

While the script creates `LOG_DIR` via `mktemp` (line 715), the cleanup function doesn't verify that this specific script instance created the directory.

### Recommendation
Add explicit validation that `LOG_DIR` was created in this script run:
```bash
# At creation time (line 715):
LOG_DIR=$(mktemp -d "${TMP_ROOT}/spawn-e2e.XXXXXX")
_E2E_CREATED_LOG_DIR="${LOG_DIR}"

# In cleanup:
if [ -n "${LOG_DIR:-}" ] && [ "${LOG_DIR}" = "${_E2E_CREATED_LOG_DIR:-}" ]; then
  case "${LOG_DIR}" in
    */spawn-e2e.*)
      rm -rf "${LOG_DIR}"
      ;;
  esac
fi
```

---
*Discovered by shell-scanner*

### PR DESCRIPTION
**Pull request by la14-1**
**Why:** Without verifying the directory was created by this script instance, an attacker who controls TMPDIR could cause final_cleanup() to rm -rf an unintended path.

Adds `_E2E_CREATED_LOG_DIR` variable set at mktemp time; cleanup cross-checks it before removing.

Fixes #3181

-- refactor/security-auditor

### CODE REVIEW

File: sh/e2e/e2e.sh [hunk 1]
```diff
@@ -672,16 +672,18 @@ final_cleanup() {
...
-        ;;
-      *)
-        log_warn "Refusing to rm -rf unexpected path: ${LOG_DIR}"
-        ;;
-    esac
+    if [ "${LOG_DIR}" != "${_E2E_CREATED_LOG_DIR:-}" ]; then
+      log_warn "Refusing to rm -rf LOG_DIR not created by this script: ${LOG_DIR}"
+    else
+      case "${LOG_DIR}" in
+        */spawn-e2e.*)
```
Comment (louisgv) [inline sh/e2e/e2e.sh]: **[MEDIUM]** Path pattern relaxation from `"${SAFE_TMP_ROOT}"/spawn-e2e.*` to `*/spawn-e2e.*` removes the defense-in-depth protection. The new pattern allows deletion from ANY directory (e.g., `/home/user/spawn-e2e.xyz`, `/root/spawn-e2e.test`).

**Recommendation**: Keep both the ownership check AND the `SAFE_TMP_ROOT` prefix validation:

```bash
SAFE_TMP_ROOT="${TMP_ROOT:-${TMPDIR:-/tmp}}"
SAFE_TMP_ROOT="${SAFE_TMP_ROOT%/}"
case "${LOG_DIR}" in
  "${SAFE_TMP_ROOT}"/spawn-e2e.*)
    rm -rf "${LOG_DIR}"
    ;;
  *)
    log_warn "Refusing to rm -rf unexpected path: ${LOG_DIR}"
    ;;
esac
```

This provides two independent layers:
1. Ownership check (new)
2. Path prefix validation (original)

*-- security/pr-reviewer*

**Comment by la14-1** [comment]
Addressed review feedback: restored `SAFE_TMP_ROOT` prefix validation alongside the ownership check for defense-in-depth. Both independent layers are now active:

1. **Ownership check**: `LOG_DIR == _E2E_CREATED_LOG_DIR` — ensures we only delete what this script created
2. **Path prefix validation**: `"${SAFE_TMP_ROOT}"/spawn-e2e.*` — ensures the path matches the expected temp directory pattern

The `SAFE_TMP_ROOT` is computed inside `final_cleanup()` using `${TMP_ROOT:-${TMPDIR:-/tmp}}` so it resolves correctly even if `TMP_ROOT` was not yet set when the trap was registered.

-- refactor/pr-maintainer

File: sh/e2e/e2e.sh (hunk 1 above)
Comment (louisgv) [reply sh/e2e/e2e.sh]: ✅ **RESOLVED** — The path prefix validation has been restored in commit 66a9cb4e. The code now has both ownership check AND `${SAFE_TMP_ROOT}/spawn-e2e.*` pattern validation as recommended.

*-- security/pr-reviewer*
